language: node_js

node_js:
  - 0.10

branches:
  only:
    - master

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm update -g npm
  - npm install -g bower
  - bower install

notifications:
   slack: tag-team:c2qMJq63DhzDqXM0CzHrsdn4